&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; **JLUFE**  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;&emsp;&ensp;**Spring 2022(Feb-Jul)**  


**<div align="center">Homework Assignment Report</div>**
<br>

**<div align="center">JILIN UNIVERSITY OF FINANCE AND ECONOMICS</div>**
<br>

**<div align="center"><span style="color:blue">College of Managment Science and Information Engineering</span></div>**

**<div align="center">MSc in <span style="color:blue">Data Science and Big Data Technology</span></div>**

**<div align="center">(2022)</div>**

<br> 

**<div align="center">MODULE: Python Statistical Analysis and Modeling</div>**

**<div align="center">Homework Assignment: 04</div>**

**<div align="center">Numpy</div>**

**<div align="center">23/05/2022</div>**

<br>

**<div align="center">Submitted by:</div>**

**<div align="center"><span style="color:blue">Milan(米兰) 0318021907632 (2005)</span></div>**
**<div align="center">QQ: <span style="color:blue">3086215265</span> | Github ID: <span style="color:blue">milaan9</span></div>**

<div class="alert alert-danger">    
    <b>Instructions: </b>


1. I have added tips and required learning resources for each question, which helps you to solve the problems. 

2. Finish the assignment on your **OWN**. **<span style="color:red">Any student find copying/sharing from classmates or internet will get '0' points!!!</span>**

3. After <span class='label label-default'>Accepting this assignment</span> from ➞ **[GitHub Clasroom link](https://classroom.github.com/a/c6DntUeh)**, Github will create private repository of the assignment in your GitHub Classroom account.

4. In your repository <span class='label label-default'>Clone</span> ➞ <span class='label label-default'>Download ZIP</span> in your computer.

5. Change your ➞ **<span style="color:blue">College</span>**, **<span style="color:blue">Major</span>**, **<span style="color:blue">Name</span>**, **<span style="color:blue">Student number</span>**, **<span style="color:blue">Class number</span>**, **<span style="color:blue">QQ number</span>**, and **<span style="color:blue">GitHub ID</span>**

6. Once you finish the Assignment **[convert your .ipynb file into PDF](https://github.com/milaan9/91_Python_Mini_Projects/tree/main/001_Convert_IPython_to_PDF)** (both **.ipynb** and **.pdf** file will be required!)

7. To submit your assignment, go to GitHub Classroom repository and <span class='label label-default'>Add file</span> ➞ <span class='label label-default'>Upload files</span> ➞ <span class='label label-default'>Commit changes</span>
    1. Replace the question (**.ipynb**) file with your solution (**.ipynb**) file.
    2. Also, upload (**.pdf**) converted file of your solution (**.ipynb**) file.

# Python Assignment 04

# Numpy ➞ <span class='label label-default'>Level 1, 2 & 3</span>

### Part A ➞ <span class='label label-default'>Level 1</span>


<div class="alert alert-info">    
    <b>Note: Please create new cell for each question </b>

<div class="alert alert-success">
    <b>1. Create a null vector of size 12 but the seventh value which is 1</b>

`💡hint: array[12]`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b>2. Create a 3x3 matrix with values ranging from 12 to 20</b>
    
`💡hint: reshape`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 3. Create a random vector of size 20 and find the mean value </b>
    
`💡hint: mean`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 4. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal </b>
    
`💡hint: np.diag`

```py
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]
```

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b>5. Create a 6x6 matrix and fill it with a checkerboard pattern </b>
    
`💡hint: array[::2]`

```py
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]
```

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b>6. Normalize a 6x6 random matrix `x`</b>
    
`💡hint: (x -mean)/std`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 7. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) </b>
    
`💡hint: np.dot` or `np.ones`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 8. Given a 1D array, negate all elements which are between 3 and 8, in place. </b>
    
`💡hint: >, <`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 9. Create a 2x2x2 array with row values ranging from 0 to 2 </b>
    
`💡hint: np.arange`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 10. How to find common values between two arrays? </b>
    
`💡hint: np.intersect1d`

In [ ]:
# Solution: 



### Part B ➞ <span class='label label-default'>Level 2</span>

<div class="alert alert-info">    
    <b>Note: Please create new cell for each question </b>

<div class="alert alert-success">
    <b> 1. Write a Python program compare two arrays using numpy </b>
    
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 2. Consider two random array A and B, check if they are equal </b>
    
`💡hint: np.allclose, np.array_equal`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 3. Create a random vector of size 9 and sort it </b>
    
`💡hint: sort`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 4. Create a 2d array with 1 on the border and 0 inside </b>
    
`💡hint: array[1:-1, 1:-1]`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 5. How to add a border (filled with 0's) around an existing array from above question? </b>
    
`💡hint: np.pad`

In [ ]:
# Solution: 



### Part C ➞ <span class='label label-default'>Level 3</span>

<div class="alert alert-info">    
    <b>Note: Please create new cell for each question </b>

<div class="alert alert-success">
    <b> 1. How to read the following file? </b>
    
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint:` save  the text in variable using `StringIO` and use `np.genfromtxt` 

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 2. How to compute ((A+B)*(-A/2)) in place (without copy)? </b>
    
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 3. How to swap two rows of an array? </b>
    
`💡hint: array[[]] = array[[]]`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b> 4. Consider a large vector A, compute A to the power of 3 using 3 different methods </b>
    
`💡hint: np.power, *, np.einsum`

In [ ]:
# Solution: 



<div class="alert alert-success">
    <b>5. How to find the most frequent value in an array?</b>
    
`💡hint: np.bincount, argmax`

In [ ]:
# Solution: 

